apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-config-map
data:
  config.json: |
    {
        "command": "/usr/sbin/httpd",
        "config_files": [
            {
                "source": "/var/lib/config-data/keystone.conf",
                "dest": "/etc/keystone/keystone.conf",
                "owner": "keystone",
                "perm": "0600"
            },
            {
                "source": "/var/lib/config-data/httpd.conf",
                "dest": "/etc/httpd/conf/httpd.conf",
                "owner": "root",
                "perm": "0644"
            },
            {
                "source": "/var/log/keystone",
                "dest": "/etc/keystone/fernet-keys/",
                "owner": "keystone:keystone",
                "perm": "0644"
            }
        ],
        "permissions": [
            {
                "path": "/var/log/keystone",
                "owner": "keystone:keystone",
                "recurse": true
            }
        ]
    }
  keystone.conf: |
    [DEFAULT]
    admin_token=foobar123
    public_bind_host=localhost.localdomain
    admin_bind_host=localhost.localdomain
    public_port=5000
    admin_port=35357

    [catalog]
    template_file=/etc/keystone/default_catalog.templates

    [database]
    connection=mysql+pymysql://keystone:foobar123@openstack-db-mariadb/keystone
    #connection=mysql+pymysql://keystone:qrQPqqKHjLb1ezhBBzVX7Btuq@192.168.127.200/keystone?read_default_group=tripleo&read_default_file=/etc/my.cnf.d/tripleo.cnf
    max_retries=-1
    db_max_retries=-1

  httpd.conf: |
    ServerTokens Prod
    ServerSignature Off
    TraceEnable Off
    PidFile run/httpd.pid
    ServerRoot "/etc/httpd"
    ServerName "localhost.localdomain"

    User apache
    Group apache

    Listen 0.0.0.0:35357
    Listen 0.0.0.0:5000

    TypesConfig /etc/mime.types

    Include conf.modules.d/*.conf
    Include conf.d/*.conf

    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    CustomLog /dev/stdout combined env=!forwarded
    CustomLog /dev/stdout proxy env=forwarded

    <VirtualHost 0.0.0.0:5000 0.0.0.0:35357>
      DocumentRoot "/var/www/cgi-bin/keystone"
    
      <Directory "/var/www/cgi-bin/keystone">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Require all granted
      </Directory>

      ErrorLog /dev/stdout
      CustomLog /dev/stdout combined env=!forwarded
      CustomLog /dev/stdout proxy env=forwarded
    
      ## WSGI configuration
      WSGIApplicationGroup %{GLOBAL}
      WSGIDaemonProcess keystone display-name=keystone group=keystone processes=3 threads=1 user=keystone
      WSGIProcessGroup keystone
      WSGIScriptAlias / "/var/www/cgi-bin/keystone/main"
      WSGIPassAuthorization On
    </VirtualHost>
---
apiVersion: v1
kind: Pod
metadata:
  name: keystone
  labels:
    app: keystone-pod
spec:
  containers:
  - name: keystone
    image: docker.io/tripleomaster/centos-binary-keystone:current-tripleo
    user: root
    #command: ['/bin/sleep', '720']
    volumeMounts:
    - mountPath: /var/lib/config-data
      readOnly: true
      name: config-data
    - mountPath: /var/lib/kolla/config_files
      readOnly: true
      name: kolla-config
    env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    lifecycle:
      postStart:
        exec:
          command: ['/bin/keystone-manage', 'bootstrap', '--bootstrap-password', 'foobar123']
  volumes:
  - name: kolla-config
    configMap:
      name: keystone-config-map
      items:
        - key: config.json
          path: config.json
  - name: config-data
    configMap:
      name: keystone-config-map
      items:
        - key: keystone.conf
          path: keystone.conf
        - key: httpd.conf
          path: httpd.conf
  initContainers:
  - name: drop-keystone
    image: docker.io/tripleomaster/centos-binary-mariadb:current-tripleo
    command:
    - 'sh'
    - '-c'
    - 'mysql -h openstack-db-mariadb -u admin -P 3306 -e "DROP DATABASE IF EXISTS keystone";'
    env:
    - name: MYSQL_PWD
      value: foobar123
  - name: keystone-db-create
    image: docker.io/tripleomaster/centos-binary-mariadb:current-tripleo
    command:
    - 'sh'
    - '-c'
    - 'mysql -h openstack-db-mariadb -u admin -P 3306 -e "CREATE DATABASE IF NOT EXISTS keystone; GRANT ALL PRIVILEGES ON keystone.* TO ''keystone''@''localhost'' IDENTIFIED BY ''foobar123'';GRANT ALL PRIVILEGES ON keystone.* TO ''keystone''@''%'' IDENTIFIED BY ''foobar123''; "'
    env:
    - name: MYSQL_PWD
      value: foobar123
  - name: keystone-db-sync
    image: docker.io/tripleomaster/centos-binary-keystone:current-tripleo
    user: root
    volumeMounts:
    - mountPath: /var/lib/config-data
      readOnly: true
      name: config-data
    - mountPath: /var/lib/kolla/config_files
      readOnly: true
      name: kolla-config
    env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: KOLLA_BOOTSTRAP
      value: 'True'
---
apiVersion: v1
kind: Service
metadata:
  name: keystone
spec:
  selector:
    app: keystone-pod
  ports:
  - protocol: TCP
    port: 5000
